import { NextResponse } from 'next/server';
import * as xlsx from 'xlsx';
import { requireAdmin } from '@/lib/admin-auth';

export async function GET() {
  const { denied } = await requireAdmin();
  if (denied) return denied;

  const data = [
    {
      'Mã Nhân Viên': '25023001',
      'Tên Công Ty': 'CÔNG TY TNHH EASTERN RUBBER CAMBODIA',
      'Chức vụ': 'Công nhân',
      'Bộ phận': 'Sản xuất',
      'Địa chỉ mail': '',
      'Đơn vị tính': 'USD',
      'Tỷ giá USD/VNĐ': '',
      'Phụ trách/quản lý trực tiếp': '',
      'Lương Cơ Bản': 600,
      'Lương thu nhập': 800,
      // ── Thu nhập ──
      'Ngày công chuẩn/tháng': 26,
      'Ngày công làm việc thực tế': 24,
      'Lương ngày công làm việc thực tế': 550,
      'Lương nghỉ nhật': '',
      'Ngày công nghỉ nhật': '',
      'Lương ngày nghỉ phép': '',
      'Ngày công nghỉ phép': '',
      'Lương ngày nghỉ Thứ 7': '',
      'Ngày công nghỉ Thứ 7': '',
      'Lương làm việc ngày Lễ/Tết': '',
      'Ngày công làm việc ngày Lễ/Tết': '',
      'Lương ngày nghỉ Lễ/Tết/Nghỉ bù': '',
      'Ngày công nghỉ Lễ/Tết/NB': '',
      'Lương ngày LVTN/Nghỉ bù': '',
      'Ngày công LVTN/NB': '',
      'Lương ngày nghỉ Chế độ': '',
      'Ngày công nghỉ Chế độ': '',
      'Giờ tăng ca': 12,
      'Lương tăng ca': 80,
      'Giờ bổ tăng ca': '',
      'Lương bổ tăng ca': '',
      'Truy lĩnh': '',
      'Diễn giải truy lĩnh': '',
      'Phụ cấp Chức danh': '',
      'Phụ cấp xăng xe': '',
      'Phụ cấp ăn ca': '',
      'Phụ cấp điện thoại': '',
      'Phụ cấp Kiêm nhiệm': '',
      'Thưởng chuyên cần': '',
      'Quà 8/3': '',
      'Quà sinh nhật, thuật lễ': '',
      'Chi phí về phép/ vé máy bay': '',
      'Tổng lương thu nhập': 800,
      // ── Khấu trừ ──
      'Bảo hiểm xã hội CCPC': '',
      'Thuế thu nhập': '',
      'Tiền ăn': '',
      'Tiền điện nước': '',
      'Số tiền đã ứng': 0,
      'Tạm ứng lương Kỳ 1': '',
      'Truy thu': '',
      'Diễn giải truy thu': '',
      'Tang chế': '',
      'Quỹ sinh nhật': '',
      'Phụ cấp ĐDCĐ': '',
      'Tổng khấu trừ': 63,
      'Thực Lãnh': 737,
    },
    {
      'Mã Nhân Viên': '25023002',
      'Tên Công Ty': 'CÔNG TY TNHH EASTERN RUBBER CAMBODIA',
      'Chức vụ': 'Công nhân',
      'Bộ phận': 'Chế biến',
      'Địa chỉ mail': '',
      'Đơn vị tính': 'USD',
      'Tỷ giá USD/VNĐ': 26137,
      'Phụ trách/quản lý trực tiếp': 'P.Chuyên đề',
      'Lương Cơ Bản': 297.21,
      'Lương thu nhập': 497.38,
      // ── Thu nhập ──
      'Ngày công chuẩn/tháng': 26,
      'Ngày công làm việc thực tế': 24,
      'Lương ngày công làm việc thực tế': 497.38,
      'Lương nghỉ nhật': 76.92,
      'Ngày công nghỉ nhật': 4,
      'Lương ngày nghỉ phép': '',
      'Ngày công nghỉ phép': '',
      'Lương ngày nghỉ Thứ 7': '',
      'Ngày công nghỉ Thứ 7': '',
      'Lương làm việc ngày Lễ/Tết': '',
      'Ngày công làm việc ngày Lễ/Tết': '',
      'Lương ngày nghỉ Lễ/Tết/Nghỉ bù': 36.26,
      'Ngày công nghỉ Lễ/Tết/NB': 1,
      'Lương ngày LVTN/Nghỉ bù': '',
      'Ngày công LVTN/NB': '',
      'Lương ngày nghỉ Chế độ': '',
      'Ngày công nghỉ Chế độ': '',
      'Giờ tăng ca': 8,
      'Lương tăng ca': 50,
      'Giờ bổ tăng ca': '',
      'Lương bổ tăng ca': '',
      'Truy lĩnh': '',
      'Diễn giải truy lĩnh': '',
      'Phụ cấp Chức danh': 30,
      'Phụ cấp xăng xe': 20,
      'Phụ cấp ăn ca': 30,
      'Phụ cấp điện thoại': 10,
      'Phụ cấp Kiêm nhiệm': '',
      'Thưởng chuyên cần': 15,
      'Quà 8/3': '',
      'Quà sinh nhật, thuật lễ': '',
      'Chi phí về phép/ vé máy bay': '',
      'Tổng lương thu nhập': 497.38,
      // ── Khấu trừ ──
      'Bảo hiểm xã hội CCPC': 8.92,
      'Thuế thu nhập': 12.50,
      'Tiền ăn': 4,
      'Tiền điện nước': 3,
      'Số tiền đã ứng': 0,
      'Tạm ứng lương Kỳ 1': 150,
      'Truy thu': '',
      'Diễn giải truy thu': '',
      'Tang chế': '',
      'Quỹ sinh nhật': 5,
      'Phụ cấp ĐDCĐ': 2,
      'Tổng khấu trừ': 185.42,
      'Thực Lãnh': 274.67,
    },
    {
      'Mã Nhân Viên': '25023003',
      'Tên Công Ty': 'CÔNG TY TNHH EASTERN RUBBER CAMBODIA',
      'Chức vụ': 'កម្មករ',
      'Bộ phận': 'ផលិតកម្ម',
      'Địa chỉ mail': '',
      'Đơn vị tính': 'KHR',
      'Tỷ giá USD/VNĐ': '',
      'Phụ trách/quản lý trực tiếp': '',
      'Lương Cơ Bản': 1500000,
      'Lương thu nhập': 2000000,
      // ── Thu nhập ──
      'Ngày công chuẩn/tháng': 26,
      'Ngày công làm việc thực tế': 26,
      'Lương ngày công làm việc thực tế': 1500000,
      'Lương nghỉ nhật': '',
      'Ngày công nghỉ nhật': '',
      'Lương ngày nghỉ phép': '',
      'Ngày công nghỉ phép': '',
      'Lương ngày nghỉ Thứ 7': '',
      'Ngày công nghỉ Thứ 7': '',
      'Lương làm việc ngày Lễ/Tết': '',
      'Ngày công làm việc ngày Lễ/Tết': '',
      'Lương ngày nghỉ Lễ/Tết/Nghỉ bù': '',
      'Ngày công nghỉ Lễ/Tết/NB': '',
      'Lương ngày LVTN/Nghỉ bù': '',
      'Ngày công LVTN/NB': '',
      'Lương ngày nghỉ Chế độ': '',
      'Ngày công nghỉ Chế độ': '',
      'Giờ tăng ca': 10,
      'Lương tăng ca': 200000,
      'Giờ bổ tăng ca': '',
      'Lương bổ tăng ca': '',
      'Truy lĩnh': '',
      'Diễn giải truy lĩnh': '',
      'Phụ cấp Chức danh': '',
      'Phụ cấp xăng xe': '',
      'Phụ cấp ăn ca': '',
      'Phụ cấp điện thoại': '',
      'Phụ cấp Kiêm nhiệm': '',
      'Thưởng chuyên cần': '',
      'Quà 8/3': '',
      'Quà sinh nhật, thuật lễ': '',
      'Chi phí về phép/ vé máy bay': '',
      'Tổng lương thu nhập': 2000000,
      // ── Khấu trừ ──
      'Bảo hiểm xã hội CCPC': '',
      'Thuế thu nhập': '',
      'Tiền ăn': '',
      'Tiền điện nước': '',
      'Số tiền đã ứng': 200000,
      'Tạm ứng lương Kỳ 1': '',
      'Truy thu': '',
      'Diễn giải truy thu': '',
      'Tang chế': '',
      'Quỹ sinh nhật': '',
      'Phụ cấp ĐDCĐ': '',
      'Tổng khấu trừ': 200000,
      'Thực Lãnh': 1800000,
    },
  ];

  const ws = xlsx.utils.json_to_sheet(data);
  const wb = xlsx.utils.book_new();
  xlsx.utils.book_append_sheet(wb, ws, 'Bảng lương');
  const buf = xlsx.write(wb, { type: 'buffer', bookType: 'xlsx' });

  return new NextResponse(buf, {
    headers: {
      'Content-Type': 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
      'Content-Disposition': 'attachment; filename="mau_bang_luong.xlsx"',
    },
  });
}
